### ISSUE TITLE
JNI errors if we compile it for ICS and above.

### ISSUE THREAD

**Issue by ghost** [yojayli/mDNSResponder-541-android#1]
Hi,

I am getting the JNI errors, while i set android:targetSdkVersion="14" and above, do you know what changes has to be made in the jnisupport.c file.

**Comment by lookatmike** [comment]
The problem I ran into was the use of a global JNIEnv in the ...Reply callback functions (e..g ServiceBrowseReply).

See the TARGET_OS_ANDROID version of SetupCallbackState; my C is extremely rusty, but that appears to assign pLoopEnv, a global JNIEnv that's set in Init, to the context's JNIEnv in the callback function. The callback then uses the global JNIEnv from there.

From at least Android 4.0 on that's a dangerous approach because JNIEnv **cannot** be shared between threads (source [here](http://developer.android.com/training/articles/perf-jni.html#JavaVM_and_JNIEnv) -- and that whole article is a fantastic read, it's helped me a lot as I've been diving into JDK/JNI).

According to the comments at the top of DNSSD.java, callbacks execute on a separate thread, so that would certainly seem to violate that rule, and explains the "thread X using JNIEnv\* from thread Y" crashes I was getting.

The solution is to have a global JavaVM (which is safe because Android allows only one JavaVM per process) instead of a global JNIEnv, and use the JavaVM's AttachCurrentThread function when you don't already have a JNIEnv and need one (as is the case in the callback functions). This approach got me up and running on Android 4.0 through 4.4. I don't have a means of testing on earlier versions, so I'm not sure about them.

I should add that the AUTO_CALLBACKS sections already in there take this approach, but the whole of AUTO_CALLBACKS is not what you want for Android.

I'm still working on cleaning up my changes to JNISupport.c (see aforementioned C rustiness), but I'll do a formal pull request once I'm happy with them. Just wanted to post this up now in case anyone happens to see this before I get around to that.

**Comment by yojayli** [comment]
com.apple.dnssd.DNSSDEmbedded runs event loop and callback in a Java thread.
The TARGET_OS_ANDROID definition (JNISupport.c) behaves as AUTO_CALLBACKS, but callbacks need to use original event loop JNIEnv instead of AttachCurrentThread().
Thanks for your comment.

**Comment by lookatmike** [comment]
Thanks for the fix! Works great, and is cleaner than what I had going.
